### ISSUE TITLE
Links to latest hboot/ruu/recoveries?

### ISSUE THREAD

**Issue by gdamjan** [OpenDesireProject/opendesireproject.org#1]
Maybe it would be appropriate to also have links to   latest hboot, ruus and recoveries on the site too?

**Comment by Mustaavalkosta** [comment]
I don't know if that's a good idea. It would indirectly indicate that we are supporting those too while we really don't. Maybe if we had a Wiki it would be appropriate place for such information but since this is just a landing page for the ODP ROMs its purpose is not to offer generic device information. I'd rather leave that part to XDA and other forums.

I'm up for a discussion though if you have valid arguments against my approach to this.

**Comment by gdamjan** [comment]
The concern about "support" is valid. Then I'd just add a single sentence to not look on the site for them and point to the forums.

Though, don't newer ROMs need an update to the radio too?

**Comment by Mustaavalkosta** [comment]
Well, our proprietary RIL library is still the same as it was with 10.1 so technically there's no need for radio upgrades if your current one just works for you.

However, there was some concerns with GPS functionality and radio in the past but I never really got very familiar with the situation because it only affected people coming from Sense ROMs so I don't know/remember the specifics.

Maybe I can add some kind of "go here for non-ODP stuff" type of link to XDA's device section. I'll play around with it as soon as I have a spare moment.

**Comment by Mustaavalkosta** [comment]
https://opendesireproject.org/index2.html

@gdamjan Would this be sufficient to you?

**Comment by gdamjan** [comment]
you might put it under the ROMs since it's of less importance.

**Comment by Mustaavalkosta** [comment]
How about now (same url)?

**Comment by gdamjan** [comment]
nice. thanks.

**Comment by Mustaavalkosta** [comment]
Ok, it's live now. :)
